language:
  - node_js

node_js:
  - "stable"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"

after_script:
  - npm run cover; cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
