language:
  - node_js

node_js:
  - stable
  - '4'

cache:
  directories:
    - $HOME/.npm
    - node_modules

after_success:
  - npm run cover
  - bash <(curl -s https://codecov.io/bash)

deploy:
  on:
    branch: master
    node: stable
  provider: npm
  email: hello@smartcar.com
  api_key: $NPM_API_TOKEN
